option(ENABLE_IPO "Enable Interprocedural Optimization, or Link Time Optimization (LTO)" ON)

if(ENABLE_IPO)
	include(CheckIPOSupported)
	check_ipo_supported(RESULT result OUTPUT output)
	if(result)
		set(CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE)
	else()
		message(SEND_ERROR "IPO not supported: ${output}")
	endif()
endif()
